#!/bin/bash

function createorganiser() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/organiser.ticket.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/organiser.ticket.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-organiser --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-organiser.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-organiser.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-organiser.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-organiser.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/organiser.ticket.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy organiser's CA cert to organiser's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/organiser.ticket.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem" "${PWD}/organizations/peerOrganizations/organiser.ticket.com/msp/tlscacerts/ca.crt"

  # Copy organiser's CA cert to organiser's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/organiser.ticket.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem" "${PWD}/organizations/peerOrganizations/organiser.ticket.com/tlsca/tlsca.organiser.ticket.com-cert.pem"

  # Copy organiser's CA cert to organiser's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/organiser.ticket.com/ca"
  cp "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem" "${PWD}/organizations/peerOrganizations/organiser.ticket.com/ca/ca.organiser.ticket.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-organiser --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-organiser --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-organiser --id.name organiseradmin --id.secret organiseradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-organiser -M "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/organiser.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-organiser -M "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls" --enrollment.profile tls --csr.hosts peer0.organiser.ticket.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/organiser.ticket.com/peers/peer0.organiser.ticket.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-organiser -M "${PWD}/organizations/peerOrganizations/organiser.ticket.com/users/User1@organiser.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/organiser.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/organiser.ticket.com/users/User1@organiser.ticket.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://organiseradmin:organiseradminpw@localhost:7054 --caname ca-organiser -M "${PWD}/organizations/peerOrganizations/organiser.ticket.com/users/Admin@organiser.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/organiser/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/organiser.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/organiser.ticket.com/users/Admin@organiser.ticket.com/msp/config.yaml"
}

function createreseller() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/reseller.ticket.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/reseller.ticket.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-reseller --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-reseller.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-reseller.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-reseller.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-reseller.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/reseller.ticket.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy reseller's CA cert to reseller's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/reseller.ticket.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem" "${PWD}/organizations/peerOrganizations/reseller.ticket.com/msp/tlscacerts/ca.crt"

  # Copy reseller's CA cert to reseller's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/reseller.ticket.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem" "${PWD}/organizations/peerOrganizations/reseller.ticket.com/tlsca/tlsca.reseller.ticket.com-cert.pem"

  # Copy reseller's CA cert to reseller's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/reseller.ticket.com/ca"
  cp "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem" "${PWD}/organizations/peerOrganizations/reseller.ticket.com/ca/ca.reseller.ticket.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-reseller --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-reseller --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-reseller --id.name reselleradmin --id.secret reselleradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-reseller -M "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/reseller.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-reseller -M "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls" --enrollment.profile tls --csr.hosts peer0.reseller.ticket.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/reseller.ticket.com/peers/peer0.reseller.ticket.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-reseller -M "${PWD}/organizations/peerOrganizations/reseller.ticket.com/users/User1@reseller.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/reseller.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/reseller.ticket.com/users/User1@reseller.ticket.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://reselleradmin:reselleradminpw@localhost:8054 --caname ca-reseller -M "${PWD}/organizations/peerOrganizations/reseller.ticket.com/users/Admin@reseller.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/reseller/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/reseller.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/reseller.ticket.com/users/Admin@reseller.ticket.com/msp/config.yaml"
}

function createattendee() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/attendee.ticket.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/attendee.ticket.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-attendee --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-attendee.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-attendee.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-attendee.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-attendee.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/attendee.ticket.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy attendee's CA cert to attendee's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/attendee.ticket.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem" "${PWD}/organizations/peerOrganizations/attendee.ticket.com/msp/tlscacerts/ca.crt"

  # Copy attendee's CA cert to attendee's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/attendee.ticket.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem" "${PWD}/organizations/peerOrganizations/attendee.ticket.com/tlsca/tlsca.attendee.ticket.com-cert.pem"

  # Copy attendee's CA cert to attendee's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/attendee.ticket.com/ca"
  cp "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem" "${PWD}/organizations/peerOrganizations/attendee.ticket.com/ca/ca.attendee.ticket.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-attendee --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-attendee --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-attendee --id.name attendeeadmin --id.secret attendeeadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-attendee -M "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/attendee.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-attendee -M "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls" --enrollment.profile tls --csr.hosts peer0.attendee.ticket.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/attendee.ticket.com/peers/peer0.attendee.ticket.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-attendee -M "${PWD}/organizations/peerOrganizations/attendee.ticket.com/users/User1@attendee.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/attendee.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/attendee.ticket.com/users/User1@attendee.ticket.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://attendeeadmin:attendeeadminpw@localhost:11054 --caname ca-attendee -M "${PWD}/organizations/peerOrganizations/attendee.ticket.com/users/Admin@attendee.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/attendee/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/attendee.ticket.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/attendee.ticket.com/users/Admin@attendee.ticket.com/msp/config.yaml"
}

function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/ticket.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/ticket.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/ticket.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/ticket.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/ticket.com/msp/tlscacerts/tlsca.ticket.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/ticket.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/ticket.com/tlsca/tlsca.ticket.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/ticket.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls" --enrollment.profile tls --csr.hosts orderer.ticket.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/ticket.com/orderers/orderer.ticket.com/msp/tlscacerts/tlsca.ticket.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/ticket.com/users/Admin@ticket.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/ticket.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/ticket.com/users/Admin@ticket.com/msp/config.yaml"
}

createorganiser
createreseller
createattendee
createOrderer
